version: "3.8"

services:
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    ports:
      - 4000:4000
    env_file: ./backend/.env.production
    networks:
      - app_network
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env.production
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
