version: "3.8"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    command: npm run dev
    environment:
      - NODE_ENV=development
    env_file: ./backend/.env
