version: "3.8"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    ports:
      - 4000:4000
    env_file: ./backend/.env.production
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env.production
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
