
FROM node:20-alpine AS development

WORKDIR /usr/src/app


COPY package*.json ./

RUN npm install

COPY prisma ./prisma

RUN npx prisma generate

COPY . .


RUN npm run build


FROM node:20-alpine AS production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --only=production

COPY prisma ./prisma
RUN npx prisma generate

COPY --from=development /usr/src/app/dist ./dist

CMD ["npm", "start"]